"""Turn raw scores into honest probabilities.

The shipped weights produce a raw score in [0, 1], but a weighted sum is not a
probability — comparing it directly against "95% confidence" would be a category
error. This module fits the mapping from a hand-labelled sample so the threshold
means what it says.

Procedure the operator follows:

1. ``python main.py run --precision`` to produce matches, each carrying the raw
   score that generated it.
2. ``python main.py validate`` to hand-label them. ~400 labels gives roughly
   +/-5% at 95% confidence; 1,000 tightens it to ~3%.
3. ``python main.py calibrate --write`` — reads those labels straight from the
   database and saves the fitted curve, which later runs load automatically.

``--labels file.csv`` remains for labels produced outside the tool.

Isotonic regression (pool-adjacent-violators) is used rather than a logistic fit
because it assumes only monotonicity — higher score, higher chance of being
right — and does not impose a shape the data may not have. It is implemented
here directly so the pipeline does not need scikit-learn for one function.
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class CalibrationResult:
    knots: list[tuple[float, float]] = field(default_factory=list)
    threshold_raw_score: float | None = None
    achieved_precision: float = 0.0
    precision_lower_bound: float = 0.0
    matched_at_threshold: int = 0
    sample_size: int = 0
    target_precision: float = 0.95

    def to_yaml(self) -> str:
        """The fitted curve as a config fragment the pipeline loads directly."""
        lines = [
            "# Fitted calibration — generated by `python main.py calibrate`.",
            "# Do not hand-edit; re-run calibrate after collecting more labels.",
            f"# sample_size: {self.sample_size}",
            f"# observed_precision: {self.achieved_precision:.4f}",
            f"# wilson_95_lower_bound: {self.precision_lower_bound:.4f}",
            "",
            "calibration:",
            f"  fitted_from_labels: {self.sample_size}",
            "  isotonic_points:",
        ]
        lines += [f"    - [{x:.4f}, {y:.4f}]" for x, y in self.knots]
        if self.threshold_raw_score is not None:
            lines += [
                "",
                "# RECOMMENDED, NOT APPLIED. Adopting this changes how many rows",
                f"# qualify, so it is left to an explicit decision:",
                f"#   recommended raw-score cut for >={self.target_precision:.0%} precision: "
                f"{self.threshold_raw_score:.4f}",
            ]
        return "\n".join(lines) + "\n"

    def write(self, path) -> None:
        from pathlib import Path as _Path

        destination = _Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(self.to_yaml(), encoding="utf-8")

    def render(self) -> str:
        lines = [
            "=" * 70,
            "  CALIBRATION RESULT",
            "=" * 70,
            f"  Labelled sample size : {self.sample_size:,}",
            f"  Target precision     : {self.target_precision:.2%}",
        ]
        if self.threshold_raw_score is None:
            lines += [
                "",
                "  NO raw-score cut point reaches the target precision with the",
                "  lower confidence bound above it. Either collect more labels or",
                "  accept a lower target. Do NOT lower the threshold without",
                "  evidence — that trades fabricated matches for apparent yield.",
                "=" * 70,
            ]
            return "\n".join(lines)

        lines += [
            f"  Raw-score cut point  : {self.threshold_raw_score:.4f}",
            f"  Precision at cut     : {self.achieved_precision:.4f}",
            f"  Lower 95% bound      : {self.precision_lower_bound:.4f}",
            f"  Labelled rows kept   : {self.matched_at_threshold:,}",
            f"  Isotonic knots fitted: {len(self.knots):,}",
            "",
            "  Run with --write to save this; the pipeline then loads it",
            "  automatically. Nothing needs to be pasted by hand.",
            "=" * 70,
        ]
        return "\n".join(lines)


def isotonic_fit(points: list[tuple[float, int]]) -> list[tuple[float, float]]:
    """Pool-adjacent-violators isotonic regression.

    ``points`` is (raw_score, label) with label in {0, 1}. Returns monotone
    non-decreasing (score, probability) knots.
    """
    if not points:
        return []

    ordered = sorted(points, key=lambda p: p[0])
    # Each block: [sum of labels, count, representative x]
    blocks: list[list[float]] = [[float(label), 1.0, x] for x, label in ordered]

    merged = True
    while merged:
        merged = False
        i = 0
        while i < len(blocks) - 1:
            left, right = blocks[i], blocks[i + 1]
            if left[0] / left[1] > right[0] / right[1]:
                # Violation of monotonicity: pool the two blocks.
                blocks[i] = [left[0] + right[0], left[1] + right[1], right[2]]
                del blocks[i + 1]
                merged = True
                i = max(0, i - 1)
            else:
                i += 1

    return [(block[2], block[0] / block[1]) for block in blocks]


def wilson_lower_bound(successes: int, total: int, z: float = 1.96) -> float:
    """Lower bound of the Wilson score interval.

    Used instead of the raw ratio so a cut point is not chosen on the strength of
    a handful of lucky labels — 10/10 correct is not evidence of 95% precision.
    """
    if total == 0:
        return 0.0
    phat = successes / total
    denominator = 1 + z * z / total
    centre = phat + z * z / (2 * total)
    margin = z * math.sqrt((phat * (1 - phat) + z * z / (4 * total)) / total)
    return max(0.0, (centre - margin) / denominator)


def choose_threshold(
    points: list[tuple[float, int]], target_precision: float = 0.95
) -> tuple[float | None, float, float, int]:
    """Lowest raw-score cut whose precision *lower bound* clears the target.

    Using the lower bound rather than the point estimate is the difference
    between "we measured 95%" and "we cannot rule out 80%".
    """
    if not points:
        return None, 0.0, 0.0, 0

    best: tuple[float | None, float, float, int] = (None, 0.0, 0.0, 0)
    for cut, _ in sorted(points, key=lambda p: p[0]):
        kept = [label for score, label in points if score >= cut]
        if len(kept) < 10:
            continue
        successes = sum(kept)
        precision = successes / len(kept)
        lower = wilson_lower_bound(successes, len(kept))
        if lower >= target_precision:
            # Lower cut => more rows kept, so the first qualifying cut is best.
            return cut, precision, lower, len(kept)
        if lower > best[2]:
            best = (None, precision, lower, len(kept))
    return best


def fit_from_labels(store, target_precision: float = 0.99) -> CalibrationResult:
    """Fit the calibration from labels collected by ``main.py validate``.

    The point of the exercise: the operator's hand-labelling stops being a
    one-off measurement and becomes the model's training data. Previously the
    only way in was a CSV the operator had to assemble themselves, so in practice
    the labels were collected and then stranded.
    """
    points = [(score, 1 if correct else 0) for score, correct in store.iter_labelled_scores()]
    if not points:
        raise ValueError(
            "no labelled rows with a raw score yet — run `python main.py validate` first"
        )
    return _fit(points, target_precision)


def fit_from_csv(path: str | Path, target_precision: float = 0.95) -> CalibrationResult:
    """Read a labelled CSV and fit the calibration."""
    points: list[tuple[float, int]] = []
    with Path(path).open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            try:
                score = float(row["raw_score"])
                label = int(float(row["correct"]))
            except (KeyError, TypeError, ValueError):
                continue
            points.append((score, 1 if label else 0))

    if not points:
        raise ValueError(
            f"no usable rows in {path}; expected columns 'raw_score' and 'correct'"
        )
    return _fit(points, target_precision)


def _fit(points: list[tuple[float, int]], target_precision: float) -> CalibrationResult:
    """Shared fit, so the CSV and database paths cannot drift apart."""
    cut, precision, lower, kept = choose_threshold(points, target_precision)
    return CalibrationResult(
        knots=isotonic_fit(points),
        threshold_raw_score=cut,
        achieved_precision=precision,
        precision_lower_bound=lower,
        matched_at_threshold=kept,
        sample_size=len(points),
        target_precision=target_precision,
    )
